pluginManagement {
    repositories {
        maven {
            name = 'FabricPublic'
            url = 'https://maven.fabricmc.net/'
        }
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
        maven {
            name = 'FabricLibraries'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'Mojang'
            url = 'https://minecraft.net'
        }
    }
}

rootProject.name = 'midpoint_visuals'
